### ISSUE TITLE
这个项目现在默认阻止登录用户使用么？

### ISSUE THREAD

**Issue by TyroneVeblen** [drunkdream/weread-exporter#109]
看了下代码，在登录的情况下，会让程序超时？

**Comment by light-266** [comment]
请问能说一下是哪个代码文件里的限制吗？我也遇到了问题

**Comment by drunkdream** [comment]
没有这样的逻辑，你是看的哪段代码

**Comment by TyroneVeblen** [comment]
> 没有这样的逻辑，你是看的哪段代码

我的错误，我理解有误，应该是使用默认头像的问题
```
    async def wait_for_avatar(self, timeout=30):
        time0 = time.time()
        while time.time() - time0 < timeout:
            avatar_url = await self._page.evaluate(
                "document.querySelector('img.wr_avatar_img') && document.querySelector('img.wr_avatar_img').getAttribute('src');"
            )
            if avatar_url is None or not avatar_url.endswith("Default.svg"):
                break
            await asyncio.sleep(5)
        else:
            raise RuntimeError("Wait for avatar timeout")
```
我使用默认的头像，所以not avatar_url.endswith("Default.svg") 为False。没有触发break，于是乎就超时了
不过现在微信读书在没有登录的情况下不会显示默认的头像，也许不要or not avatar_url.endswith("Default.svg")也可以？

**Comment by drunkdream** [comment]
这个问题我之前也发现过，不过比较麻烦的是没有找到更好用来判断页面登录态生效的标志，考虑到大部分用户的微信头像都不是默认的，就保留了这个逻辑；目前只能本地修改下这里的判断逻辑来规避这个问题

**Comment by TyroneVeblen** [comment]
> 这个问题我之前也发现过，不过比较麻烦的是没有找到更好用来判断页面登录态生效的标志，考虑到大部分用户的微信头像都不是默认的，就保留了这个逻辑；目前只能本地修改下这里的判断逻辑来规避这个问题

确实，没有更好的逻辑也只能这样了。感谢您的回复。
