### ISSUE TITLE
 status is invalid,

### ISSUE THREAD

**Issue by 376924098** [drunkdream/weread-exporter#22]
(base)  bin@bindeMacBook-Pro  ~/VsCodeProjects/weread-exporter   main ●  python -m weread_exporter -b 7023271071a3505370215dc -o epub
/Users/bin/VsCodeProjects/weread-exporter/weread_exporter/__main__.py:129: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
[2023-05-20 14:53:12,487][INFO]Exporting book 7023271071a3505370215dc
[2023-05-20 14:53:12,705][WARNING]Book 7023271071a3505370215dc status is invalid, stop exporting

**Comment by drunkdream** [comment]
这本书下架了

**Comment by 376924098** [comment]
> 这本书下架了

没有下架呀
https://weread.qq.com/web/bookDetail/7023271071a3505370215dc
https://weread.qq.com/web/reader/7023271071a3505370215dcka87322c014a87ff679a21ea

**Comment by drunkdream** [comment]
![image](https://github.com/drunkdream/weread-exporter/assets/10045603/9cd5162a-d5cc-44aa-b8fb-bfe79090e1df)

**Comment by 376924098** [comment]
这么奇怪吗，我打开是有的
