### ISSUE TITLE
正文中的换行符

### ISSUE THREAD

**Issue by paulcx** [drunkdream/weread-exporter#35]
有些书在抽取的时候把网页上显示的换行也带了下来，是否有办法去除这些换行符？

**Comment by drunkdream** [comment]
可以截图给个例子吗

**Comment by paulcx** [comment]
例如现在抽取出来的文本许多像下面这样（猜测是解析canvas的时候带过来的？）：

```
如果我们生命的每一秒钟得无限重复，我们就会像耶稣被
钉在十字架上一样被钉在永恒上。这一想法是残酷的。
在永恒轮回的世界里，一举一动都承受着不能承受的责任重负。
这就是尼采说永恒轮回的想法是最沉重的负担（
das schwerste Gewicht）的缘故吧。如果永恒轮回是最沉重
的负担，那么我们的生活，在这一背景下，却可在其整个的灿
烂轻盈之中得以展现。但是，重便真的残酷，而轻便真的美丽？
最沉重的负担压迫着我们，让我们屈服于它，把我们压到地上。
但在历代的爱情诗中，女人总渴望承受一个男性身体的重量。
于是，最沉重的负担同时也成了最强盛的生命力的影像。
负担越重，我们的生命越贴近大地，它就越真切实在。
相反，当负担完全缺失，人就会变得比空气还轻，就会飘起来，
就会远离大地和地上的生命，人也就只是一个半真的存在，
其运动也会变得自由而没有意义。那么，到底选择什么？
是重还是轻？巴门尼德[插图]早在公元前六世纪就给自己
提出过这个问题。在他看来，宇宙是被分割成一个个对立
的二元：明与暗，厚与薄，热与冷，在与非在。他把对立的一
极视为正极（明、热、薄、在），另一极视为负极。
这种正负之极的区分在我们看来可能显得幼稚简单。除了在这个问
```

希望是下面这样，正文里不换行：

如果我们生命的每一秒钟得无限重复，我们就会像耶稣被钉在十字架上一样被钉在永恒上。这一想法是残酷的。在永恒轮回的世界里，一举一动都承受着不能承受的责任重负。这就是尼采说永恒轮回的想法是最沉重的负担（das schwerste Gewicht）的缘故吧。如果永恒轮回是最沉重的负担，那么我们的生活，在这一背景下，却可在其整个的灿烂轻盈之中得以展现。但是，重便真的残酷，而轻便真的美丽？最沉重的负担压迫着我们，让我们屈服于它，把我们压到地上。但在历代的爱情诗中，女人总渴望承受一个男性身体的重量。于是，最沉重的负担同时也成了最强盛的生命力的影像。负担越重，我们的生命越贴近大地，它就越真切实在。相反，当负担完全缺失，人就会变得比空气还轻，就会飘起来，就会远离大地和地上的生命，人也就只是一个半真的存在，其运动也会变得自由而没有意义。那么，到底选择什么？是重还是轻？巴门尼德[插图]早在公元前六世纪就给自己提出过这个问题。在他看来，宇宙是被分割成一个个对立的二元：明与暗，厚与薄，热与冷，在与非在。他把对立的一极视为正极（明、热、薄、在），另一极视为负极。这种正负之极的区分在我们看来可能显得幼稚简单。除了在这个问

**Comment by drunkdream** [comment]
最好给下具体的链接，正常情况下是会自动进行合并的，但如果识别成像代码或是诗之类的，就不会合并了

**Comment by paulcx** [comment]
例如这个本书：https://weread.qq.com/web/bookDetail/f9332790722d7b6df93f432
大概2/3（可以测试第三篇之后）都不能合并。

另外发现一个bug，出现timeout后会报报错，无法自动跳转到下一章节，提示pyppeteer错误，并卡在那里。可能还涉及nested asyncio问题，我就直接把重试3次的代码屏蔽掉了，如果出现chapter fail错误直接就page.close再重启，跳过进行下一篇章循环。

**Comment by drunkdream** [comment]
> 例如这个本书：https://weread.qq.com/web/bookDetail/f9332790722d7b6df93f432

![image](https://github.com/drunkdream/weread-exporter/assets/10045603/92199c49-5fa8-421d-9c4d-0a4c06efa1bc)

我把这本书下载下来看，没有看到你说的这个问题，除了有些生僻字用的图片导致生成的格式不太对以外，其他都还好

**Comment by paulcx** [comment]
[262-263.md](https://github.com/drunkdream/weread-exporter/files/12062958/262-263.md)
这是下载的其中一章，为什么不一样？

**Comment by drunkdream** [comment]
> [262-263.md](https://github.com/drunkdream/weread-exporter/files/12062958/262-263.md) 这是下载的其中一章，为什么不一样？

这个是中间文件，全部下载完之后会进行一次处理，就包括进行行合并的逻辑

**Comment by paulcx** [comment]
> > [262-263.md](https://github.com/drunkdream/weread-exporter/files/12062958/262-263.md) 这是下载的其中一章，为什么不一样？
> 
> 这个是中间文件，全部下载完之后会进行一次处理，就包括进行行合并的逻辑

能说下合并的逻辑和对应的额代码吗？

**Comment by drunkdream** [comment]
https://github.com/drunkdream/weread-exporter/blob/main/weread_exporter/export.py#L66

处理逻辑在这里，但是我发现你这边生成的原始markdown文件有点奇怪，正常的应该是这样的：

```
## 第三节　癌胚抗原检测

癌胚抗原( carcinoembryonic antigen，CEA)是一种由胎儿胃肠道上皮组织、
胰和肝细胞所合成的糖蛋白。CEA类似于AFP，均为胚胎期产生的胎儿癌性抗原
组，CEA基因家族包括2个亚组的17个活化基因，属于非器官特异性肿瘤相关抗
原。

## 一、检测方法

目前CEA的常用检测方法有ELISA、CLIA、ECLIA、金标记免疫渗滤层析、RI
A、时间分辨荧光免疫分析法及流式荧光免疫检测技术，其中以ELISA法最为常
用。

(一) ELISA法 【原理】

采用针对不同抗原决定簇的两个单克隆抗体分别制备成包被板和酶结合物，利
用ELISA双抗体夹心法原理定量检测人血清标本中CEA含量。

【试剂】

试剂组成:包被有抗CEA单克隆抗体的微孔板、一系列浓度的标准品、酶标记
的抗CEA单克隆抗体、酶显色底物溶液以及质控物、浓缩洗涤液、终止液等。

【操作】

按试剂盒使用说明书或实验室制定的SOP进行操作，主要操作流程如下:

设定和加载标准品、质控物和待测标本→加入酶标记的抗CEA单克隆抗体→温
育反应→洗涤→加入酶显色底物溶液→温育反应→终止→比色。
```

你给的[262-263.md](https://github.com/drunkdream/weread-exporter/files/12062958/262-263.md)内容多了很多换行，会没法正常处理

**Comment by paulcx** [comment]
> https://github.com/drunkdream/weread-exporter/blob/main/weread_exporter/export.py#L66
> 
> 处理逻辑在这里，但是我发现你这边生成的原始markdown文件有点奇怪，正常的应该是这样的：
> 
> ```
> ## 第三节　癌胚抗原检测
> 
> 癌胚抗原( carcinoembryonic antigen，CEA)是一种由胎儿胃肠道上皮组织、
> 胰和肝细胞所合成的糖蛋白。CEA类似于AFP，均为胚胎期产生的胎儿癌性抗原
> 组，CEA基因家族包括2个亚组的17个活化基因，属于非器官特异性肿瘤相关抗
> 原。
> 
> ## 一、检测方法
> 
> 目前CEA的常用检测方法有ELISA、CLIA、ECLIA、金标记免疫渗滤层析、RI
> A、时间分辨荧光免疫分析法及流式荧光免疫检测技术，其中以ELISA法最为常
> 用。
> 
> (一) ELISA法 【原理】
> 
> 采用针对不同抗原决定簇的两个单克隆抗体分别制备成包被板和酶结合物，利
> 用ELISA双抗体夹心法原理定量检测人血清标本中CEA含量。
> 
> 【试剂】
> 
> 试剂组成:包被有抗CEA单克隆抗体的微孔板、一系列浓度的标准品、酶标记
> 的抗CEA单克隆抗体、酶显色底物溶液以及质控物、浓缩洗涤液、终止液等。
> 
> 【操作】
> 
> 按试剂盒使用说明书或实验室制定的SOP进行操作，主要操作流程如下:
> 
> 设定和加载标准品、质控物和待测标本→加入酶标记的抗CEA单克隆抗体→温
> 育反应→洗涤→加入酶显色底物溶液→温育反应→终止→比色。
> ```
> 
> 你给的[262-263.md](https://github.com/drunkdream/weread-exporter/files/12062958/262-263.md)内容多了很多换行，会没法正常处理

https://github.com/drunkdream/weread-exporter/blob/main/weread_exporter/export.py#L66 这部分代码我的理解是，将已经解析下载好的markdown文件再进行一次处理，例如遇到代码块的时候进行换行处理。

不过我的问题可能是，在pre_process_markdown之前的markdown文件就已经包含了很多换行，因此pre_process_markdown也无法进行去除。能看一下你解析这本书的原始markdown文件吗，我再对照一下，看看为什么不一样？
