### ISSUE TITLE
OSError: no library called "cairo-2" was found

### ISSUE THREAD

**Issue by hal9000123** [drunkdream/weread-exporter#76]
no library called "cairo" was found
cannot load library 'D:\GTK\GTK2-Runtime Win64\bin\libcairo-2.dll': error 0x7f
cannot load library 'libcairo.so.2': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo.so.2' 
cannot load library 'libcairo.2.dylib': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo.2.d
ylib'

下载gtk配置好路径也不行

**Comment by whitewatercn** [comment]
我参考这个在macOS上弄好了 https://stackoverflow.com/a/78511437/19541857
