### ISSUE TITLE
大佬，求助。运行后没有任何反应。

### ISSUE THREAD

**Issue by xfgy1234** [drunkdream/weread-exporter#83]
<img width="1169" alt="截屏2024-05-29 10 51 54" src="https://github.com/drunkdream/weread-exporter/assets/62039987/1e25dcde-6941-4824-a89f-deb36c088c8d">

**Comment by xfgy1234** [comment]
环境是macos arm64平台，用Windows11虚拟机跑的，模拟x64。macos直接跑会出现这个问题。brew install cairo 也无法解决，怀疑是库不支持arm64平台的原因。
<img width="676" alt="image" src="https://github.com/drunkdream/weread-exporter/assets/62039987/e3c0bc5e-b05a-4852-99ef-c07cb421a655">

**Comment by drunkdream** [comment]
直接在cmd里运行，不要在powershell里运行

**Comment by xfgy1234** [comment]
大佬，感谢您回复。我刚刚尝试在cmd里运行，依然没有反应。请问如何能看到具体报错日志，方便分析一下。我是小白，请见谅。
<img width="843" alt="image" src="https://github.com/drunkdream/weread-exporter/assets/62039987/9c41a746-8ba2-4f2d-ba8e-87a6601799ae">

**Comment by xfgy1234** [comment]
大佬 确实是我的m芯片mac电脑的问题 我换了台普通的windows电脑 就运行正常了。但也希望帮助您解决一下mac电脑适配的问题

**Comment by xfgy1234** [comment]
#67 已经有人给出mac运行的解答 感谢
